#include "protocol_api.h"
#include "stdio.h"

/**
 * @brief Main function that runs the SAP Protocol test.
 *
 * This function simulates the key exchange and stealth address generation
 * process within the SAP protocol. It includes key pair generation,
 * computation of the shared secret and view tag by the sender,
 * and stealth address generation by both the sender and recipient.
 * The test is passed if the stealth addresses generated by the sender
 * and recipient match.
 *
 * @return 0 if the test passes, indicating successful execution;
 *         otherwise, returns early on failure.
 */

int main() {

    uint8_t k_pub[KYBER_PUBLICKEYBYTES];  
    uint8_t v_pub[KYBER_PUBLICKEYBYTES];
    uint8_t k_priv[KYBER_SECRETKEYBYTES];
    uint8_t v_priv[KYBER_SECRETKEYBYTES];

    uint8_t ephemeral_pub_key[CIPHERTEXT_BYTES];
    uint8_t view_tag;
    uint8_t stealth_pub_key_sender[STEALTH_ADDRESS_BYTES];
    uint8_t stealth_pub_key_reciever[STEALTH_ADDRESS_BYTES];
    uint8_t ss[KYBER_SSBYTES];
    uint8_t ss2[KYBER_SSBYTES];

    printf("SAP Protocol: ");

    crypto_kem_keypair(k_pub, k_priv);
    crypto_kem_keypair(v_pub, v_priv);

    printf("KYBER_K: %d\n", KYBER_K);

    sender_computes_stealth_pub_key_and_viewtag(stealth_pub_key_sender, ephemeral_pub_key,
        &view_tag, v_pub, k_pub);
    
    
    recipient_computes_stealth_pub_key(stealth_pub_key_reciever,
        k_pub, ephemeral_pub_key, v_priv);
    
    for (int i = 0; i < STEALTH_ADDRESS_BYTES; i++) {
        if (stealth_pub_key_reciever[i] != stealth_pub_key_sender[i]) {
            printf("Test FAILED!\n");
            return 0;
        }
    }
    printf("Test PASSED!\n");
}